# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [9]:
# Create and solve the relevant system of equations

# Day 1
import numpy as np

A = np.array([[29,41],[23,41]])
B = np.array([490,448])

X = np.linalg.solve(A,B)
np.round(X)
print(X)
print('A bag of coffee costs {}, and a bad of tea {}'.format(X[0],X[1]))

[7. 7.]
A bag of coffee costs 7.000000000000001, and a bad of tea 6.999999999999999


In [6]:
# Just to double check the results
# According to the theory:

print(A.dot(X))
print(B)

[490. 448.]
[490 448]


In [7]:
# Describe your result
# Results are explained above as part of the print, each is worth 7 dollars, and results were double checked

This was the fast way, alternatively it can be done using np.matrix.
See below:

In [17]:
A = np.matrix([[29,41],[23,41]])
B = np.matrix([490,448])

A_inv = np.linalg.inv(A)
B = B.T
X = A_inv.dot(B)
display(X)

matrix([[7.],
        [7.]])

Same results!!!

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [22]:
# Create and solve the relevant system of equations

A = np.matrix([[12,3],[8,3]])
B = np.matrix([162,122])

A_inv = np.linalg.inv(A)
B = B.T

X = A_inv.dot(B)
X

print('The price for the admissions was {} per child, and {} per adult'.format(X[0], X[1]))

The price for the admissions was [[10.]] per child, and [[14.]] per adult


In [23]:
# Describe your result
# Results were describe above as part of the workflow...

## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [26]:
# Create and solve the relevant system of equations
# t + c + o = 7
# 2t = o ==> 2t + 0c - 1o = 0 (twice as many tomatoes as onions, means 2 tomatoes per onion)
# 0.75t + 1.25c + 0.5o = 5.25

A = np.matrix([[1,1,1],[2,0,-1],[0.75,1.25,0.5]])
B = np.matrix([7,0,5.25])

A_inv = np.linalg.inv(A)

X = A_inv.dot(B.T)
print(X)

print('There are {} tomatoes, {} carrots, and {} onions'.format(X[0], X[1], X[2]))

[[1.75]
 [1.75]
 [3.5 ]]
There are [[1.75]] tomatoes, [[1.75]] carrots, and [[3.5]] onions


Describe your result

The results given on the lab are wrong. The reason is because twice as an object A compared to B means mathematically: 2A = B and not the other way around as this was define. 


In order to obtain those number you will need twice the number of onions per tomato, and that would be 2o = 1t, and therefore that equation would be: t + 0c - 2o = 0, doing it that way you will get different amounts. See below:

In [28]:
A = np.matrix([[1,1,1], [1, 0, -2], [0.75,1.25,0.5]])
B = np.matrix([7,0,5.25])

A_inv = np.linalg.inv(A)

X = A_inv.dot(B.T)
print(X)

# the order of my X was [t, c, o], therefore:

print('There are {} tomatoes, {} carrots, and {} onions in the recipe'.format(X[0],X[1],X[2]))

[[4.]
 [1.]
 [2.]]
There are [[4.]] tomatoes, [[1.]] carrots, and [[2.]] onions in the recipe


## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [31]:
# Create and solve the relevant system of equations

A = np.matrix([[1,1,1],[0.1,0.2,0.3],[2,0,-1]])
B = np.matrix([1240,276,0])

A_inv = np.linalg.inv(A)

X = A_inv.dot(B.T)
print('The 1 bedroom rent is {}, the 2 bedroom {}, and the 3 bedroom {} Dollars'.format(X[0],X[1],X[2]))

The 1 bedroom rent is [[280.]], the 2 bedroom [[400.]], and the 3 bedroom [[560.]] Dollars


In [32]:
# Describe your result
# Price description is above

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 